language: ruby
ruby:
- 2.2
deploy:
  provider: rubygems
  api_key:
    secure: mYw6EXZPeEKkKENcUbY8BnQZgcwHjQGA/2LD0lBVFz4LsWPUkmhE7d/y4sfY82X1ROnqmH3d15z+NKB2hdt98+mNZpMjlMoWS9XYm+SSV37qRbxTxG5MltBYZq7wERI2RW3Kc+mXIu5/9Jpd7AP2hwqtQDvKzcxbQw4i6KxGMAR1+JYvJC/U9BRYp8Vz0EBATUjkzTe+FYEHWy5OMoF4IdtVwXtQor+ejNlK2Mxa2GK+STH0rpfb2lDZBWBdX36G85sTfSZFuCO7wk/QMyLM5FmuD3vg544Ed4ddlU8AP26T0XsrnRUGxRM0fwidcAoKlAY/qAVig1ebNwaM9TUKotDQasP6Ad3m/O2ybJqjWlFJoz7h09LfLutB8Ke3K998581UM8GNV1gT9D0voRGYgrn1D17/7xlIDIb8SksPFmtKQDqXofeoSvPCA5g+dneLDa/7FC6FTrlEopuViwy1Bh8BaKl0cIfgcu2gu/68SaHsgiU+c7GENuSRjz/gtkRzt6NaEWKwio26Rt5U0LaiBWu5w9zYrkx4m7gJ2JfZ+KitvUMPAPZHOvWqhglHwxlMwE50x8XJ5ZZg26zybmtei5OTka36zUEWi7JJVJIWmQmCnN3pknQeAzTc29twqN42FSkeZHs8B2UYgAFvjfEKXoZulgHMQzBfsYSTens7+Ys=
  gem: marathon_deploy
  on:
    tags: true
    repo: eBayClassifiedsGroup/marathon_deploy
env:
  global:
    secure: 5TDe4PAOoKK3CLw6DKhiUx0gGDpJnVIs0XFLVj4Ndi701vNXeaT0knzwnTKrNSFrN3fCHXjgl/6YpB4cCDaIq+ZPVCmZka/G19EB73SWi3LPMLt8IXTXLL7Vk0sPeEtR2wGv4rgqgmw/NGVPNrQYPkYFoxx+k4be66nCZIsTFFaRJ3/N2cKamOz7spGbgC6TfGGGPP/0HjSF0FV8vFZc3vgwFWmaH2LWTmGX/aQe7qW9aW1ESN6u8E2O499PpmB5+c5PFknTTJBw4khTIT5TwCA3hPdOYksibuPP/0QcPb7Tf9GEbYnVECihVFC9lGm7CPEOQdtx3FTUHCUJN49SJE1tSlTctuB5nxZ9eqfFNfvFD5YPpymsCOXNbjOEEIr3kxsGlqJEiH4+IG3HV7+jo9NBrSYOp9HxQcSQRcv5t8geyfmcRmi0j5+o/TQ0UUaIRN6uVfevoKmCW7k2Eu1PDWvxrUlkmToxptFj6BIYahBlwveMqdQoOhuSO4CFU85MwvyI8nMBro5mzOiy5TXhaQiZ+4KyLvUyyKmW7/O9HDSsoYjNImgDvzGD0XJOWqeHdDlaf/NA+QwbVFmSHiErUQ4KPTF0JqpUa680iORP9HRUTL79dNfK25Bx+51KMdhr87KRkUE3gRNl0mJ5Zgnba+jOeds8t64hGE6J+n4WSGc=
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
